import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import path from'node:path';import{fileURLToPath}from'node:url';
const source=fs.readFileSync(process.env.SHIELD_PRIMARY_QUERY_SOURCE||fileURLToPath(new URL('../src/recovered/electron/ipc/zapret-manager.js',import.meta.url)),'utf8');
const worker=fs.readFileSync(process.env.SHIELD_PRIMARY_WORKER_SOURCE||fileURLToPath(new URL('../src/component-worker-entry.js',import.meta.url)),'utf8');
function slice(s,a,b){const x=s.indexOf(a),y=s.indexOf(b,x+a.length);assert.ok(x>=0&&y>x,'Actual production function boundaries required');return s.slice(x,y).trim();}
const reader=slice(source,'async readDnsProtectionServiceIdentity() {','async readDnsProtectionStandaloneIdentity() {'),execute=slice(source,'async execPowerShell(','async fetchText('),quote=slice(source,'function psQuote(value) {','function buildCommandResult('),compact=slice(worker,'function compactWorkerNativeQueryDiagnostic(','function replyWorker(');
const executable='C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',wrapper='C:\\Own fixture\\egoistshield-zapret-service.exe';
function fixture(stderr,success=false){const calls=[];const raw=Object.assign(new Error('synthetic raw cause'),{code:1,killed:true,signal:'SIGTERM',stdout:'',stderr});
const context=vm.createContext({path:path.win32,performance,Buffer,Date,Error,SyntaxError,resolveWindowsExecutable:()=>executable,execFileAsync$1:(exe,args,opts)=>{calls.push({exe,args:[...args],opts:{...opts}});const p=success?Promise.resolve({stdout:JSON.stringify({state:'Stopped',pid:0,birth:null,image:wrapper})}):Promise.reject(raw);p.child={pid:12345};return p;}});
vm.runInContext(source.match(/^var SERVICE_NAME = "[A-Za-z0-9_-]+";$/m)[0]+'\n'+quote+'\nglobalThis.reader=({'+reader+'}).readDnsProtectionServiceIdentity;\nglobalThis.execute=({'+execute+'}).execPowerShell;\nglobalThis.compact='+compact+';',context,{timeout:1000});
const owner={getServiceWrapperPaths:()=>({wrapperPath:wrapper}),execPowerShell:context.execute};return{run:()=>context.reader.call(owner),generic:()=>context.execute.call(owner,'own inert query',8000),compact:context.compact,calls,raw};}
const marker=(stage,n)=>'egoist-native-identity|'+stage+'|'+n+'\n';
const full=['script-start','utility-import-ready','cim-import-ready','service-query-ready','process-query-ready','serialization-ready'].map((s,n)=>marker(s,n*50)).join('');
test('actual identity query emits fixed private markers; stdout execution/env/deadline contract unchanged',async()=>{const f=fixture('',true);assert.equal((await f.run()).state,'Stopped');assert.equal(f.calls.length,1);const c=f.calls[0];assert.equal(c.exe,executable);assert.equal(c.opts.timeout,8000);assert.equal(Object.hasOwn(c.opts,'env'),false);assert.deepEqual(c.args.slice(0,3),['-NoProfile','-NonInteractive','-Command']);
for(const stage of['script-start','utility-import-ready','cim-import-ready','service-query-ready','process-query-ready','process-query-skipped','serialization-ready'])assert.ok(c.args[3].includes('egoist-native-identity|'+stage+'|'));
assert.match(c.args[3],/\[System.Diagnostics.Stopwatch\]::StartNew\(\)/);assert.match(c.args[3],/Owned Zapret service image mismatch/);assert.match(c.args[3],/Owned Zapret wrapper identity unavailable/);assert.match(c.args[3],/ConvertTo-Json -Compress/);assert.doesNotMatch(c.args[3],/Console\]::Out|PSModulePath|Start-Service|Stop-Service|Set-Dns/);
});
test('actual timeout diagnostic passes only observed stage+bounded timing through actual worker whitelist',async()=>{for(const stages of[full,full.replace('process-query-ready','process-query-skipped')]){const f=fixture(stages+'#< CLIXML\nsynthetic-secret-path-SID-tail');await assert.rejects(f.run(),e=>{const d=f.compact(e.nativeQueryDiagnostic);assert.equal(d.kind,'terminated');assert.equal(d.timeoutMs,8000);assert.equal(d.identityStage,'serialization-ready');assert.equal(d.identityStageElapsedMs,250);assert.equal(Object.hasOwn(d,'pid'),false);assert.ok(!JSON.stringify(d).includes('secret'));assert.ok(!JSON.stringify(d).includes('cause'));assert.equal(e.cause.cause,f.raw);return true;});}});
test('actual parser preserves partial observations without claiming operation success',async()=>{const f=fixture(marker('script-start',0)+marker('utility-import-ready',34));await assert.rejects(f.run(),e=>{const d=f.compact(e.nativeQueryDiagnostic);assert.equal(d.kind,'terminated');assert.equal(d.identityStage,'utility-import-ready');assert.equal(d.identityStageElapsedMs,34);return true;});});
test('actual parser rejects unknown/malformed/oversized/nonmonotonic/raw markers; original failure retained',async()=>{const invalid=['', 'synthetic raw SID/path', marker('secret-path',0), marker('script-start',0)+marker('cim-import-ready',1),marker('script-start',10)+marker('utility-import-ready',9),marker('script-start',0)+marker('utility-import-ready',8001),marker('script-start',0)+'egoist-native-identity|utility-import-ready|NaN\n',marker('script-start',0)+marker('script-start',1),marker('script-start',0)+'raw\n'+marker('utility-import-ready',1),marker('script-start',0)+'x'.repeat(4096)];
for(const payload of invalid){const f=fixture(payload);await assert.rejects(f.run(),e=>{const d=f.compact(e.nativeQueryDiagnostic);assert.equal(d.kind,'terminated');assert.equal(d.timeoutMs,8000);assert.equal(Object.hasOwn(d,'identityStage'),false);assert.equal(Object.hasOwn(d,'identityStageElapsedMs'),false);return true;});}});
test('generic actual execPowerShell remains stage-free even for marker-shaped stderr',async()=>{const f=fixture(full);await assert.rejects(f.generic(),e=>{assert.equal(e.powerShellDiagnostic.kind,'terminated');assert.equal(Object.hasOwn(e.powerShellDiagnostic,'identityStage'),false);return true;});assert.equal(f.calls[0].opts.timeout,8000);assert.equal(Object.hasOwn(f.calls[0].opts,'env'),false);});
test('actual worker whitelist refuses forged fields and never emits raw/cause/path/PID',()=>{const f=fixture('');for(const change of[{identityStage:'raw secret'},{identityStageElapsedMs:-1},{identityStageElapsedMs:8001},{identityStageElapsedMs:1.5},{identityStageElapsedMs:'2'},{timeoutMs:9000}]){const d=f.compact({kind:'terminated',timeoutMs:8000,identityStage:'script-start',identityStageElapsedMs:0,pid:12345,raw:'secret',cause:{secret:true},path:'secret',...change});assert.equal(Object.hasOwn(d,'identityStage'),false);assert.equal(Object.hasOwn(d,'identityStageElapsedMs'),false);assert.ok(!JSON.stringify(d).includes('secret'));}assert.equal(f.compact({kind:'secret',identityStage:'script-start',identityStageElapsedMs:0}),undefined);});
