import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs';
import vm from 'node:vm';
const source=process.env.LAGOM_DNS_APPLY_MANAGER_SOURCE ?? new URL('../src/recovered/electron/ipc/system-doh-service-manager.js',import.meta.url);
const context=vm.createContext({URL,Buffer,AbortController,setTimeout,clearTimeout,console,path,process,promisify:value=>value,execFile:async()=>{},resolveWindowsExecutable:value=>value,normalizeSystemDohUrl:value=>value,normalizeSystemDohLocalAddress:value=>value,parseSystemDohUrl:()=>({serverPort:8443}),buildSystemDohLoopbackCandidates:()=>['127.0.0.1','127.0.0.2']});
vm.runInContext(fs.readFileSync(source,'utf8')+'\n;globalThis.api={SystemDohManager,buildSystemDohServiceXml}',context);
const {SystemDohManager,buildSystemDohServiceXml}=context.api;
async function fixture({installed=false,running=false,ready=false,owned=true}={}) {
 const root=await fs.promises.mkdtemp(path.join(process.env.LAGOM_TASK_WORK ?? process.env.TEMP,'apply-recovery-'));
 const statePath=path.join(root,'state.json');const configPath=path.join(root,'config.json'); const events=[];
 const saved={url:'https://provider.example:8443/profile',localAddress:'127.0.0.1',localPort:53,startedAt:'synthetic-generation',pid:12};
 if(installed){await fs.promises.writeFile(statePath,JSON.stringify(saved));await fs.promises.writeFile(configPath,'saved bootstrap config');}
 const readState=async()=>{try{return JSON.parse(await fs.promises.readFile(statePath,'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw e;}};
 const manager=Object.create(SystemDohManager.prototype);
 Object.assign(manager,{coreService:null,statePath,configPath,
 status:async()=>{const value=await readState();return {enabled:installed&&!!value,serviceInstalled:installed,serviceRunning:running,serviceState:!installed?'not-installed':running?'running':'stopped',running:running&&ready,verified:running&&ready,currentUrl:value?.url,localAddress:value?.localAddress,localPort:value?.localPort,nativeManaged:false};},
 readManagedState:readState,writeManagedState:async value=>{events.push('save-state');await fs.promises.writeFile(statePath,JSON.stringify(value));},
 queryServiceStatus:async()=>({installed,running,state:!installed?'not-installed':running?'running':'stopped',pid:22}),
 isManagedServiceOwned:async()=>owned, ensureManagedRuntimeInstalled:async()=>({runtimePath:'synthetic-owned-runtime'}),ensureServiceWrapperInstalled:async()=>{},
 stopAndRemoveInternal:async()=>{events.push('initial-remove');installed=false;running=false;await fs.promises.rm(statePath,{force:true});await fs.promises.rm(configPath,{force:true});},
 prepareConfig:async()=>{events.push('write-config');await fs.promises.writeFile(configPath,'new bootstrap config');},writeServiceWrapperConfig:async()=>events.push('wrapper-config'),
 installService:async()=>{events.push('install');installed=true;},configureServiceAutostartRecovery:async()=>events.push('recovery-policy'),
 startServiceInternal:async()=>{events.push('start');running=true;},waitUntilReady:async()=>ready,
 removeServiceInternal:async()=>{events.push('rollback-remove');installed=false;running=false;},stopLegacyStandaloneRuntime:async()=>events.push('rollback-kill'),
 clearManagedState:async()=>{events.push('rollback-clear');await fs.promises.rm(statePath,{force:true});await fs.promises.rm(configPath,{force:true});},readLogTail:async()=>null,invalidateStatusCache:()=>{},
 });
 return {manager,events,saved,root,readState,setReady:v=>ready=v,isInstalled:()=>installed,config:()=>fs.promises.readFile(configPath,'utf8')};
}
test('transient upstream failure retains newly running owned resolver, state and config for Core recovery',async()=>{const f=await fixture();const result=await f.manager.apply(f.saved.url);assert.equal(result.running,false);assert.equal(result.verified,false);assert.equal(result.enabled,true);assert.equal(result.readinessPending,true);assert.equal(result.ownedResolverRetained,true);assert.equal(f.isInstalled(),true);assert.equal((await f.readState()).url,f.saved.url);assert.equal(await f.config(),'new bootstrap config');assert.equal(f.events.includes('rollback-remove'),false);const saved=await f.readState();const beforeRetry=[...f.events];f.setReady(true);assert.equal((await f.manager.apply(f.saved.url)).verified,true);assert.deepEqual(f.events,beforeRetry);assert.deepEqual(await f.readState(),saved);});
test('same saved provider retry starts stopped owned resolver without deleting state or rewriting bootstrap',async()=>{const f=await fixture({installed:true});const result=await f.manager.apply(f.saved.url);assert.equal(result.enabled,true);assert.equal(await f.config(),'saved bootstrap config');assert.equal(f.events.includes('initial-remove'),false);assert.equal(f.events.includes('write-config'),false);assert.ok(f.events.includes('start'));});
test('foreign stopped service refuses saved-provider retry without cleanup or rewriting state',async()=>{const f=await fixture({installed:true,owned:false});await assert.rejects(f.manager.apply(f.saved.url),/принадлежност|owned/i);assert.deepEqual(f.events,[]);assert.equal(await f.config(),'saved bootstrap config');});
test('readiness failure with changed saved generation refuses destructive rollback',async()=>{const f=await fixture();f.manager.waitUntilReady=async()=>{await fs.promises.writeFile(f.manager.statePath,JSON.stringify({...f.saved,startedAt:'new-external-generation'}));return false;};await assert.rejects(f.manager.apply(f.saved.url),/измен|generation/i);assert.equal(f.isInstalled(),true);assert.equal((await f.readState()).startedAt,'new-external-generation');assert.equal(f.events.includes('rollback-remove'),false);});
test('real bind/start failure still takes confirmed rollback path',async()=>{const f=await fixture();f.manager.startServiceInternal=async()=>{throw new Error('bind: address already in use');};await assert.rejects(f.manager.apply(f.saved.url),/bind:/);assert.ok(f.events.includes('rollback-remove')&&f.events.includes('rollback-clear'));});
test('unreadable SCM after readiness timeout preserves service and saved files without fallback cleanup',async()=>{const f=await fixture();f.manager.waitUntilReady=async()=>{f.manager.queryServiceStatus=async()=>({installed:true,running:false,state:'unknown'});return false;};await assert.rejects(f.manager.apply(f.saved.url),/неизвестно/i);assert.equal(f.isInstalled(),true);assert.equal((await f.readState()).url,f.saved.url);assert.equal(f.events.includes('rollback-remove'),false);});
test('bind failure observed after start still confirms rollback and tries the next loopback',async()=>{const f=await fixture();f.manager.readLogTail=async()=> 'bind: address already in use';await assert.rejects(f.manager.apply(f.saved.url),/bind:/);assert.equal(f.events.filter(value=>value==='rollback-remove').length,2);assert.equal(f.events.filter(value=>value==='rollback-clear').length,2);});

test('boot recovery with temporary upstream failure keeps automatic saved resolver and config',async()=>{for(const running of [false,true]){const f=await fixture({installed:true,running});const before=await f.readState();const result=await f.manager.recover({enabled:true,url:f.saved.url,localAddress:f.saved.localAddress});assert.equal(result.verified,false);assert.equal(f.isInstalled(),true);assert.deepEqual(await f.readState(),before);assert.equal(await f.config(),'saved bootstrap config');assert.equal(f.events.includes('initial-remove')||f.events.includes('rollback-remove'),false);}});
test('DNS wrapper boot intent is automatic and SYSTEM worker config sets Tcpip/Afd dependencies',async()=>{const xml=buildSystemDohServiceXml({runtimePath:'C:/owned/xray-system-doh.exe',configPath:'C:/owned/config.json',workingDirectory:'C:/owned',serviceLogDirectory:'C:/owned/logs'});assert.match(xml,/<startmode>Automatic<\/startmode>/);assert.match(xml,/<delayedAutoStart>false<\/delayedAutoStart>/);const calls=[];const f=await fixture();f.manager.execSc=async args=>calls.push(Array.from(args));delete f.manager.configureServiceAutostartRecovery;await f.manager.configureServiceAutostartRecovery();assert.ok(calls.some(args=>args.join('|')==='config|EgoistShieldSystemDoH|start=|auto'));assert.ok(calls.some(args=>args.join('|')==='config|EgoistShieldSystemDoH|depend=|Tcpip/Afd'));});
