import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {isIP} from 'node:net';
import {createHash} from 'node:crypto';
import {loadRecovered} from './load-recovered.mjs';
const names=['ZapretManager','parseZapretDnsTransportConfiguration','readZapretDnsTransportSnapshot','buildZapretDnsKernelGuard','applyZapretDnsTransportExclusions','splitWindowsCommandLine'];
function api(extra={}){return loadRecovered('electron/ipc/zapret-manager',{path,isIP,createHash,promises:fs,package_default:{version:'3.8.0'},promisify:fn=>fn,execFile:()=>{},escapeXmlText:v=>v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;'),logger:{warn(){}},...extra},names);}
const baseFilter='!impostor and !loopback and tcp and (tcp.DstPort == 443 or tcp.SrcPort == 443 or tcp.DstPort == 8443 or tcp.SrcPort == 8443)',sdk=api(),endpoints=[{address:'192.0.2.10',port:8443}];
const normal=c=>[...sdk.splitWindowsCommandLine(c)],guard=c=>normal(c).find(x=>x.startsWith('--wf-raw=')),plain=v=>JSON.parse(JSON.stringify(v));
function config(url='https://dns.example:8443/private-token'){return{state:{url,localAddress:'127.0.0.1',localPort:53},config:{inbounds:[{tag:'dns-in',protocol:'dokodemo-door',listen:'127.0.0.1',port:53}],dns:{tag:'doh-upstream',servers:[{address:url}],hosts:{'dns.example':['192.0.2.10']}}}};}
test('protected primary config yields exact IP/port and exposes no token',()=>{const c=config(),r=sdk.parseZapretDnsTransportConfiguration(c.state,c.config);assert.deepEqual(plain(r),endpoints);assert.doesNotMatch(JSON.stringify(r),/private-token|dns.example/);});
test('numeric IPv4/IPv6 and explicit fallback retain exact ports',()=>{const c=config('https://192.0.2.11/dns-query');c.config.dns.servers.push('https://[2001:db8::1]:8443/dns-query');assert.deepEqual(plain(sdk.parseZapretDnsTransportConfiguration(c.state,c.config)),[{address:'192.0.2.11',port:443},{address:'2001:db8::1',port:8443}]);});
for(const kind of ['url','port','local','hosts','tag','duplicate'])test('inconsistent DNS '+kind+' is rejected with masked error',()=>{const c=config();if(kind==='url')c.config.dns.servers[0].address='https://different.example/secret2';if(kind==='port')c.state.localPort=54;if(kind==='local')c.state.localAddress='0.0.0.0';if(kind==='hosts')c.config.dns.hosts['dns.example']=['not-ip'];if(kind==='tag')c.config.dns.tag='foreign';if(kind==='duplicate')c.config.dns.hosts['DNS.EXAMPLE']=['192.0.2.11'];assert.throws(()=>sdk.parseZapretDnsTransportConfiguration(c.state,c.config),e=>!/private-token|secret2/.test(e.message));});
test('kernel guard excludes both directions of exact TCP endpoint, preserves other ports/strategies',()=>{const r=sdk.applyZapretDnsTransportExclusions('--wf-tcp=443,8443 --wf-udp=443 --filter-tcp=8443 --dpi-desync=fake --new --filter-udp=443',endpoints,baseFilter);assert.match(guard(r),/ip.DstAddr != 192.0.2.10 or tcp.DstPort != 8443/);assert.match(guard(r),/ip.SrcAddr != 192.0.2.10 or tcp.SrcPort != 8443/);assert.equal(normal(r).filter(x=>x==='--new').length,1);assert.ok(normal(r).includes('--wf-udp=443'));assert.ok(normal(r).includes('--filter-tcp=8443'));assert.equal(normal(r).filter(x=>x.startsWith('--wf-raw=')).length,1);});
test('existing raw-part boolean precedence and quoted user args survive',()=>{const before='--wf-tcp=8443 "--wf-raw-part=outbound or inbound" "--hostlist-exclude=C:\\My Lists\\keep.txt"',r=sdk.applyZapretDnsTransportExclusions(before,endpoints,'!loopback and ((outbound or inbound) or tcp)');assert.match(guard(r),/^--wf-raw=\(!loopback and \(\(outbound or inbound\) or tcp\)\) and /);assert.ok(normal(r).includes('--wf-raw-part=outbound or inbound'));assert.ok(normal(r).includes('--hostlist-exclude=C:\\My Lists\\keep.txt'));});
test('complete raw filter gets guard rather than an ignored raw-part',()=>{const r=sdk.applyZapretDnsTransportExclusions('"--wf-raw=outbound or inbound" "--wf-raw-part=tcp.DstPort == 443"',endpoints),a=normal(r);assert.match(a.find(x=>x.startsWith('--wf-raw=')),/^--wf-raw=\(outbound or inbound\) and \(true and \(not tcp/);assert.ok(a.includes('--wf-raw-part=tcp.DstPort == 443'));});
for(const raw of ['--wf-raw=@C:\\filter.txt','--wf-raw-part=@C:\\filter.txt','--wf-raw-part=a --wf-raw-part=b','--wf-raw','--wf-raw=x --wf-raw=y'])test('file-backed/ambiguous kernel filter fails closed: '+raw,()=>assert.throws(()=>sdk.applyZapretDnsTransportExclusions(raw,endpoints),/Kernel|kernel|фильтр/));
test('reapplication replaces old managed guard and keeps user policy once',()=>{const a=sdk.applyZapretDnsTransportExclusions('"--wf-raw-part=outbound or inbound" --wf-tcp=443,8443',endpoints,'!loopback and ((outbound or inbound) or tcp)');assert.deepEqual(normal(sdk.applyZapretDnsTransportExclusions(a,endpoints)),normal(a));const b=sdk.applyZapretDnsTransportExclusions(a,[{address:'192.0.2.11',port:443}]);assert.doesNotMatch(b,/192.0.2.10/);assert.match(b,/192.0.2.11/);assert.match(guard(b),/^--wf-raw=\(!loopback and \(\(outbound or inbound\) or tcp\)\) and /);assert.ok(normal(sdk.applyZapretDnsTransportExclusions(b,[])).includes('--wf-raw-part=outbound or inbound'));});
test('endpoint validator rejects injection/CIDR/scope/invalid port',()=>{for(const e of[{address:'192.0.2.10 or true',port:443},{address:'192.0.2.0/24',port:443},{address:'fe80::1%2',port:443},{address:'192.0.2.10',port:65536}])assert.throws(()=>sdk.buildZapretDnsKernelGuard([e]),/endpoints/);});
async function fixture(t,active=true){const root=await fs.mkdtemp(path.join(process.env.LAGOM_TEST_TEMP??process.env.TEMP,'zapret-dns-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const z=path.join(root,'Runtime','Zapret'),doh=path.join(root,'Runtime','SystemDoH');await fs.mkdir(path.join(z,'service-wrapper'),{recursive:true});await fs.mkdir(doh,{recursive:true});const c=config();await fs.writeFile(path.join(doh,'state.json'),JSON.stringify(c.state));await fs.writeFile(path.join(doh,'config.json'),JSON.stringify(c.config));const{ZapretManager}=api(),m=new ZapretManager('resources','app','user',z),xmlPath=m.getServiceWrapperPaths().xmlPath,xml=m.buildServiceWrapperXml('Selected',path.join(z,'core','bin','winws.exe'),'--wf-tcp=8443 --filter-tcp=8443 --hostlist-domains=discord.media');await fs.writeFile(xmlPath,xml);let running=active,pid=active?100:0;const events=[];m.readDnsKernelCaptureFilter=async()=>baseFilter;m.listIntegratedWinwsProcesses=async()=>[];m.queryService=async()=>({installed:true,running,state:running?'RUNNING':'STOPPED'});m.readDnsProtectionServiceIdentity=async()=>({state:running?'Running':'Stopped',pid,birth:running?'2026-10-02T14:00:00Z':null,image:m.getServiceWrapperPaths().wrapperPath});m.assertNoExternalConflict=async()=>{};m.stopServiceInternal=async()=>{events.push('stop');running=false;pid=0;};m.startWrappedService=async()=>{events.push('start');running=true;pid=200;};m.waitForServiceState=async()=>{};m.waitForIntegratedWinwsStart=async()=>true;return{root,z,doh,m,xmlPath,xml,events,running:()=>running};}
test('bounded real-file reader validates protected state/config',async t=>{const f=await fixture(t),r=await sdk.readZapretDnsTransportSnapshot(f.doh);assert.deepEqual(plain(r.endpoints),endpoints);assert.match(r.fingerprint,/^[0-9a-f]{64}$/);});
test('oversized/orphaned DNS files reject before Zapret mutation',async t=>{const f=await fixture(t);await fs.writeFile(path.join(f.doh,'config.json'),' '.repeat(65537));await assert.rejects(f.m.refreshSystemDohTransportProtection(),/конфигураци/);assert.deepEqual(f.events,[]);await fs.rm(path.join(f.doh,'state.json'));await fs.writeFile(path.join(f.doh,'config.json'),'{}');await assert.rejects(f.m.refreshSystemDohTransportProtection(),/конфигураци/);assert.deepEqual(f.events,[]);});
test('protected root junction/symlink is rejected',async t=>{const f=await fixture(t),link=path.join(f.root,'linked');await fs.symlink(f.doh,link,process.platform==='win32'?'junction':'dir');await assert.rejects(sdk.readZapretDnsTransportSnapshot(link),/каталог/);});
test('generation readback rejects config changed between bounded reads',async t=>{const f=await fixture(t);let opens=0;const custom={...fs,open:async(...a)=>{if(++opens===4){const c=config();c.config.dns.hosts['dns.example']=['192.0.2.11'];await fs.writeFile(path.join(f.doh,'config.json'),JSON.stringify(c.config));}return fs.open(...a);}};await assert.rejects(api({promises:custom}).readZapretDnsTransportSnapshot(f.doh),/изменил(?:ась|ся)/);});
test('running owned Zapret refreshes once, preserving strategy flags and DNS bytes',async t=>{const f=await fixture(t),state=await fs.readFile(path.join(f.doh,'state.json')),cfg=await fs.readFile(path.join(f.doh,'config.json'));assert.equal((await f.m.refreshSystemDohTransportProtection()).changed,true);assert.deepEqual(f.events,['stop','start']);const xml=await fs.readFile(f.xmlPath,'utf8');assert.match(xml,/wf-raw=/);assert.match(xml,/hostlist-domains=discord.media/);assert.deepEqual(await fs.readFile(path.join(f.doh,'state.json')),state);assert.deepEqual(await fs.readFile(path.join(f.doh,'config.json')),cfg);assert.equal((await f.m.refreshSystemDohTransportProtection()).changed,false);assert.deepEqual(f.events,['stop','start']);});
test('stopped Zapret persistent XML refresh stays stopped, no startup policy change',async t=>{const f=await fixture(t,false),r=await f.m.refreshSystemDohTransportProtection();assert.equal(r.changed,true);assert.equal(r.state,'stopped');assert.equal(f.running(),false);assert.deepEqual(f.events,[]);});
test('foreign wrapper XML aborts before stop/write',async t=>{const f=await fixture(t);await fs.writeFile(f.xmlPath,f.xml.replace('<id>EgoistShieldZapret</id>','<id>Foreign</id>'));await assert.rejects(f.m.refreshSystemDohTransportProtection(),/принадлежащей/);assert.deepEqual(f.events,[]);});
test('pending/unknown SCM state aborts before stop/write',async t=>{const f=await fixture(t);f.m.readDnsKernelCaptureFilter=async()=>baseFilter;f.m.queryService=async()=>({installed:true,running:false,state:'STOP_PENDING'});await assert.rejects(f.m.refreshSystemDohTransportProtection(),/Состояние/);assert.deepEqual(f.events,[]);});
test('changed wrapper PID/birth aborts before stop',async t=>{const f=await fixture(t);let calls=0;const orig=f.m.readDnsProtectionServiceIdentity;f.m.readDnsProtectionServiceIdentity=async()=>({...await orig(),pid:++calls===1?100:101});await assert.rejects(f.m.refreshSystemDohTransportProtection(),/изменилась/);assert.deepEqual(f.events,[]);});
test('changed DNS generation aborts before stopping Zapret',async t=>{const f=await fixture(t);let calls=0;const orig=f.m.readSystemDohTransportSnapshot.bind(f.m);f.m.readSystemDohTransportSnapshot=async()=>({...await orig(),fingerprint:++calls===1?'one':'two'});await assert.rejects(f.m.refreshSystemDohTransportProtection(),/изменилась/);assert.deepEqual(f.events,[]);});
test('start failure restores owned XML/runtime and masks secrets',async t=>{const f=await fixture(t);let attempts=0;const start=f.m.startWrappedService;f.m.startWrappedService=async()=>{if(++attempts===1)throw Error('https://secret.example/private-token');return start();};await assert.rejects(f.m.refreshSystemDohTransportProtection(),e=>/прежний Zapret восстановлен/.test(e.message)&&!/private-token/.test(e.message));assert.equal(await fs.readFile(f.xmlPath,'utf8'),f.xml);assert.equal(f.running(),true);});
test('failed Zapret rollback is reported, DNS bytes remain untouched',async t=>{const f=await fixture(t),cfg=await fs.readFile(path.join(f.doh,'config.json'));f.m.startWrappedService=async()=>{throw Error('failure');};await assert.rejects(f.m.refreshSystemDohTransportProtection(),/подтвердить восстановление Zapret; DNS сохранён/);assert.deepEqual(await fs.readFile(path.join(f.doh,'config.json')),cfg);});
async function standaloneFixture(t){
 const f=await fixture(t,false),statePath=path.join(f.z,'.egoistshield-standalone.json');
 let live=true,pid=100,currentArgs='--wf-tcp=8443 --filter-tcp=8443 --hostlist-domains=discord.media';
 const state=()=>JSON.stringify({pid,profile:'Selected',startedAt:'2026-10-02T14:00:00Z'});
 await fs.writeFile(statePath,state());
 f.m.listIntegratedWinwsProcesses=async()=>live?[{pid}]:[];
 f.m.readDnsProtectionStandaloneIdentity=async()=>({pid,birth:'2026-10-02T14:00:00Z',image:path.join(f.z,'core','bin','winws.exe'),arguments:currentArgs,profile:'Selected',stateFingerprint:createHash('sha256').update(await fs.readFile(statePath)).digest('hex')});
 f.m.stopDnsProtectionStandaloneIdentity=async()=>{f.events.push('stop-standalone');live=false;};
 f.m.startDnsProtectionStandaloneArgs=async(args,profile)=>{assert.equal(profile,'Selected');f.events.push('start-standalone');live=true;pid=200;currentArgs=args;await fs.writeFile(statePath,state());};
 return {...f,statePath,live:()=>live,args:()=>currentArgs};
}
test('standalone refresh preserves actual custom args/profile and mode, idempotent; no service mutation',async t=>{const f=await standaloneFixture(t),r=await f.m.refreshSystemDohTransportProtection();assert.equal(r.state,'standalone');assert.equal(r.changed,true);assert.deepEqual(f.events,['stop-standalone','start-standalone']);assert.match(f.args(),/wf-raw=/);assert.match(f.args(),/hostlist-domains=discord.media/);assert.equal(await fs.readFile(f.xmlPath,'utf8'),f.xml);assert.equal((await f.m.refreshSystemDohTransportProtection()).changed,false);assert.deepEqual(f.events,['stop-standalone','start-standalone']);});
test('standalone unknown ownership/foreign PID fails before stop',async t=>{const f=await standaloneFixture(t);f.m.listIntegratedWinwsProcesses=async()=>[{pid:999}];await assert.rejects(f.m.refreshSystemDohTransportProtection(),/Процесс standalone/);assert.deepEqual(f.events,[]);});
test('standalone recycled PID or changed args aborts before stop',async t=>{const f=await standaloneFixture(t);let count=0;const orig=f.m.readDnsProtectionStandaloneIdentity;f.m.readDnsProtectionStandaloneIdentity=async()=>({...await orig(),birth:++count===1?'2026-10-02T14:00:00Z':'2026-10-02T14:00:01Z'});await assert.rejects(f.m.refreshSystemDohTransportProtection(),/изменился/);assert.deepEqual(f.events,[]);});
test('standalone active/cancelled selection is not restarted',async t=>{const f=await standaloneFixture(t);f.m.autoSelectController=new AbortController();f.m.autoSelectController.abort();await assert.rejects(f.m.refreshSystemDohTransportProtection(),/Автоподбор/);assert.deepEqual(f.events,[]);});
test('standalone off request between native readback and restart remains off',async t=>{const f=await standaloneFixture(t);const stop=f.m.stopDnsProtectionStandaloneIdentity;f.m.stopDnsProtectionStandaloneIdentity=async identity=>{await stop(identity);await fs.rm(f.statePath);};await assert.rejects(f.m.refreshSystemDohTransportProtection(),/изменение режима не переопределено, DNS сохранён/);assert.equal(f.live(),false);assert.deepEqual(f.events,['stop-standalone']);});
test('standalone service start race aborts before killing old standalone',async t=>{const f=await standaloneFixture(t);let count=0;f.m.queryService=async()=>++count<2?{installed:true,running:false,state:'STOPPED'}:{installed:true,running:true,state:'RUNNING'};await assert.rejects(f.m.refreshSystemDohTransportProtection(),/изменился/);assert.deepEqual(f.events,[]);});
test('standalone start failure restores previous exact args/profile without touching DNS',async t=>{const f=await standaloneFixture(t),before=f.args(),cfg=await fs.readFile(path.join(f.doh,'config.json'));const start=f.m.startDnsProtectionStandaloneArgs;let calls=0;f.m.startDnsProtectionStandaloneArgs=async(...a)=>{if(++calls===1)throw Error('private-token');return start(...a);};await assert.rejects(f.m.refreshSystemDohTransportProtection(),e=>/прежний режим восстановлен, DNS сохранён/.test(e.message)&&!/private-token/.test(e.message));assert.equal(f.args(),before);assert.equal(f.live(),true);assert.deepEqual(await fs.readFile(path.join(f.doh,'config.json')),cfg);});
test('native wf-save multiline base persists as one-line full raw filter and refreshes repeatedly',async t=>{const native='!impostor and !loopback and\n(\n tcp and (tcp.DstPort == 8443 or tcp.SrcPort == 8443)\n)';const a=sdk.applyZapretDnsTransportExclusions('--wf-tcp=8443',endpoints,native);assert.doesNotMatch(guard(a),/[\r\n]/);assert.deepEqual(normal(sdk.applyZapretDnsTransportExclusions(a,endpoints)),normal(a));const f=await fixture(t);f.m.readDnsKernelCaptureFilter=async()=>native;assert.equal((await f.m.refreshSystemDohTransportProtection()).changed,true);assert.equal((await f.m.refreshSystemDohTransportProtection()).changed,false);assert.deepEqual(f.events,['stop','start']);});
