using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Security.AccessControl;
using System.Security.Principal;
using EgoistShield.Service;
namespace CoreDnsMigrationPreflightRegression;
internal static class Program
{
 static string Work="",Xray=""; static int Passed,Failed;
 const string Url="https://fixture.example:8443/private/profile?tenant=fixture";
 static void Require(bool value,string reason){if(!value)throw new Exception(reason);}
 static async Task Check(string name,Func<Task> action){try{await action();Passed++;Console.WriteLine("PASS: "+name);}catch(Exception error){Failed++;Console.WriteLine("FAIL: "+name+" -> "+error);}}
 static Task Sync(Action action){action();return Task.CompletedTask;}
 static JsonElement Parse(string text){using var json=JsonDocument.Parse(text);return json.RootElement.Clone();}
 static JsonElement State(bool? enabled=null){var state=new JsonObject{["url"]=Url,["localAddress"]="127.0.0.1",["localPort"]=53};if(enabled.HasValue)state["enabled"]=enabled.Value;return JsonSerializer.SerializeToElement(state);}
 static JsonElement Legacy()=>JsonDefaults.ToElement(new{
  log=new{loglevel="warning",error=@"C:\fixture\old-error.log",access="none"},
  dns=new{tag="doh-upstream",hosts=new Dictionary<string,object>{["fixture.example"]="203.0.113.44",["local.fixture"]=new[]{"192.0.2.44"}},servers=new[]{new{address=Url,skipFallback=true,queryStrategy="UseIPv4"}},disableFallback=true,queryStrategy="UseIPv4"},
  inbounds=new[]{new{tag="dns-in",listen="127.0.0.1",port=53,protocol="dokodemo-door",settings=new{network="tcp,udp",address="1.1.1.1",port=53}}},
  outbounds=new[]{new{protocol="freedom",streamSettings=new{security="tls",tlsSettings=new{fingerprint="chrome",allowInsecure=false,serverName="fixture.example",pinnedPeerCertSha256=new[]{"fixture-pin"}}}}},routing=new{domainStrategy="AsIs"}});
 static bool Migrate(JsonElement value,out JsonElement result)=>SystemDohRecoveryPreflight.TryBuildMigrationConfiguration(State(),value,out result,out _);
 static async Task<int> Main(string[] args)
 {
  if(args.Length==6&&args[0]=="--contained-owner-fixture"){string own=Path.GetFullPath(args[1]),image=Path.GetFullPath(args[2]);Require(image.StartsWith(own+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)&&Path.GetFullPath(Environment.ProcessPath!).StartsWith(own+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase),"Fixture host/image must be inside own runtime");int port=int.Parse(args[3]),upstream=int.Parse(args[4]);Require(args[5].Length==32,"Unique fixture identity required");using var deadline=new CancellationTokenSource(8000);await SystemDohRecoveryPreflight.ProbeContainedMigrationCandidateAsync(image,Candidate(port,upstream),port,false,deadline.Token);return 0;}
  Require(args.Length==4&&args[0]=="--work"&&args[2]=="--xray"&&Path.IsPathFullyQualified(args[1]),"--work <own runtime> --xray <own fixture copy>");Work=Path.GetFullPath(args[1]);Xray=Path.GetFullPath(args[3]);
  Require(Xray.StartsWith(Work+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)&&File.Exists(Xray),"Use own isolated Xray copy");Directory.CreateDirectory(Work);
  await Check("legacy missing marker/cache refuses old reader but migration prepares compatible candidate",()=>Sync(()=>{var old=Legacy();Require(!SystemDohServiceHealthProbe.TryReadConfiguration(State(),old,out _),"Fixture already has marker");Require(Migrate(old,out var next)&&SystemDohServiceHealthProbe.TryReadConfiguration(State(),next,out _),"Legacy migration denied");}));
  await Check("only fixed marker cache and existing log.error change; exact private TLS/routing/listeners remain",()=>Sync(()=>{var old=Legacy();Require(Migrate(old,out var next),"Migration denied");var node=JsonNode.Parse(next.GetRawText())!;
   Require(node["dns"]!["serveStale"]!.GetValue<bool>()&&node["dns"]!["serveExpiredTTL"]!.GetValue<int>()==120&&node["log"]!["error"]!.GetValue<string>()=="","Patch missing");
   node["dns"]!.AsObject().Remove("serveStale");node["dns"]!.AsObject().Remove("serveExpiredTTL");node["dns"]!["hosts"]!.AsObject().Remove("health.egoist.invalid");node["log"]!["error"]=@"C:\fixture\old-error.log";
   Require(JsonNode.DeepEquals(node,JsonNode.Parse(old.GetRawText())),"Unapproved provider/bootstrap/TLS/routing/log change");}));
  await Check("conflicting health marker rejects without source mutation",()=>Sync(()=>{var node=JsonNode.Parse(Legacy().GetRawText())!;node["dns"]!["hosts"]!["health.egoist.invalid"]="192.0.2.1";string before=node.ToJsonString();Require(!Migrate(Parse(before),out _)&&node.ToJsonString()==before,"Conflicting marker admitted");}));
  await Check("disabled runtime and allowInsecure TLS policy reject",()=>Sync(()=>{Require(!SystemDohRecoveryPreflight.TryBuildMigrationConfiguration(State(false),Legacy(),out _,out _),"Disabled admitted");var node=JsonNode.Parse(Legacy().GetRawText())!;node["outbounds"]![0]!["streamSettings"]!["tlsSettings"]!["allowInsecure"]=true;Require(!Migrate(JsonSerializer.SerializeToElement(node),out _),"TLS skip admitted");}));
  await Check("extra provider changed private URL or wildcard listener reject",()=>Sync(()=>{foreach(int variant in new[]{0,1,2}){var node=JsonNode.Parse(Legacy().GetRawText())!;if(variant==0)node["dns"]!["servers"]!.AsArray().Add("https://foreign.invalid/dns-query");if(variant==1)node["dns"]!["servers"]![0]!["address"]="https://foreign.invalid/dns-query";if(variant==2)node["inbounds"]![0]!["listen"]="0.0.0.0";Require(!Migrate(JsonSerializer.SerializeToElement(node),out _),"Foreign provider/listener admitted");}}));
  await Check("duplicate JSON properties reject instead of last-value interpretation",()=>Sync(()=>Require(!Migrate(Parse("{\"dns\":{},\"dns\":"+Legacy().GetProperty("dns").GetRawText()+",\"log\":{},\"inbounds\":[]}"),out _),"Duplicate admitted")));
  await Check("leaf-v1 digest normalizes object order whitespace decimal spelling but preserves array order/types",()=>Sync(()=>{string digest=SystemDohRecoveryPreflight.MigrationDigest(Parse("{\"z\":[true,null,1.00],\"é\":\"😀\"}"));Require(digest==SystemDohRecoveryPreflight.MigrationDigest(Parse("{ \"é\":\"😀\", \"z\":[true,null,1e0] }")),"Semantic mismatch");Require(digest!=SystemDohRecoveryPreflight.MigrationDigest(Parse("{\"z\":[null,true,1],\"é\":\"😀\"}"))&&digest!=SystemDohRecoveryPreflight.MigrationDigest(Parse("{\"z\":[true,null,\"1\"],\"é\":\"😀\"}")),"Arrays or types collapsed");Console.WriteLine("VECTOR leaf-v1: "+digest);}));
  await Check("actual Program extra/repeated flags reject sanitized before production access",async()=>{foreach(var request in new[]{new[]{SystemDohMigrationPreflightCommand.Flag,"--state-root",Work},new[]{SystemDohMigrationPreflightCommand.Flag,SystemDohMigrationPreflightCommand.Flag}}){var output=new StringWriter();var old=Console.Out;int code;try{Console.SetOut(output);code=await EgoistShield.Service.Program.Main(request);}finally{Console.SetOut(old);}var result=Parse(output.ToString());Require(code==2&&!result.GetProperty("ready").GetBoolean()&&!output.ToString().Contains(Work),"Extra args executed or leaked");}});
  await Check("elevated token and installed host guard reject before private reads",()=>Sync(()=>{bool denied=false;try{SystemDohMigrationPreflightCommand.AssertAdministrator(true,false,false);}catch(UnauthorizedAccessException){denied=true;}Require(denied,"Unelevated admitted");SystemDohMigrationPreflightCommand.AssertAdministrator(true,true,false);denied=false;try{VpnRuntimeHost.ResolveInstalledRoot();}catch(UnauthorizedAccessException){denied=true;}Require(denied,"Uninstalled test host admitted");}));
  await Check("primary manual-off or changed URL refuses independent of stale backup/running journal",()=>Sync(()=>{Require(!SystemDohRecoveryPreflight.MigrationSettingsAllow(JsonDefaults.ToElement(new{systemDohEnabled=false,systemDohUrl=Url}),Url),"Manual off admitted");Require(!SystemDohRecoveryPreflight.MigrationSettingsAllow(JsonDefaults.ToElement(new{systemDohEnabled=true,systemDohUrl="https://other.invalid/dns-query"}),Url),"Changed URL admitted");Require(SystemDohRecoveryPreflight.MigrationSettingsAllow(JsonDefaults.ToElement(new{systemDohEnabled=true,systemDohUrl=Url}),Url),"Valid private intent denied");Require(!SystemDohRecoveryPreflight.MigrationIntentAllows(Parse("{\"schemaVersion\":1,\"owner\":\"EgoistShield\",\"services\":{\"EgoistShieldSystemDoH\":{\"running\":false}}}")),"Journal off admitted");}));
  await Check("DNS intent digest notices manual off while unrelated profile reserialization remains allowed",()=>Sync(()=>{var one=JsonDefaults.ToElement(new{systemDohEnabled=true,systemDohUrl=Url,profile="old"});var two=JsonDefaults.ToElement(new{profile="new",systemDohUrl=Url,systemDohEnabled=true});var off=JsonDefaults.ToElement(new{systemDohEnabled=false,systemDohUrl=Url});Require(SystemDohRecoveryPreflight.MigrationActivationDigest(one)==SystemDohRecoveryPreflight.MigrationActivationDigest(two)&&SystemDohRecoveryPreflight.MigrationActivationDigest(one)!=SystemDohRecoveryPreflight.MigrationActivationDigest(off),"Intent scope wrong");}));
  await Check("real leased current state denies writing/deletion and enforces size/private ACL bounds",FileLeasesAsync);
  await Check("native private ACL refuses inherited legacy Users READ before canonical conversion",()=>Sync(PrivateAclMigration));
  await Check("exact wrapper argv rejects extra config/confdir/positional and XML entities",()=>Sync(()=>{string image=Path.Combine(Work,"owned.exe"),config=Path.Combine(Work,"config.json");Require(SystemDohRecoveryPreflight.MigrationArgumentsSelect("run -config \""+config+"\"",image,config,false),"Managed argv denied");foreach(string extra in new[]{" --config foreign.json"," --confdir foreign"," positional"," --"})Require(!SystemDohRecoveryPreflight.MigrationArgumentsSelect("run -config \""+config+"\""+extra,image,config,false),"Extra argument admitted");bool denied=false;try{SystemDohRecoveryPreflight.AssertMigrationWrapper(Encoding.UTF8.GetBytes("<!DOCTYPE service [<!ENTITY x SYSTEM 'file:///fixture'>]><service><id>&x;</id></service>"),image,config);}catch(System.Xml.XmlException){denied=true;}Require(denied,"XML entity admitted");}));
  await Check("actual held native command line parent and birth reject foreign generations",NativeFactsAsync);
  await Check("healthy old generation permits actual fresh Xray candidate without recovery veto",()=>RealCandidateAsync(false,false));
  await Check("production generation change after healthy candidate rejects migration",()=>RealCandidateAsync(false,true));
  await Check("actual unready candidate timeout preserves old process and cleans candidate",()=>RealCandidateAsync(true,false));
  await Check("contained candidate cancellation cleans original handle within 1.5 seconds",CancellationAsync);
  await Check("forced unique owner exit kills only its candidate and releases high ports",ForcedOwnerExitAsync);
  Console.WriteLine($"Migration preflight: passed={Passed}, failed={Failed}; productionWrites=false; fallback=false");return Failed==0?0:1;
 }
 static async Task FileLeasesAsync(){string path=Path.Combine(Work,"primary-"+Guid.NewGuid().ToString("N")+".json");await File.WriteAllTextAsync(path,"{\"fixture\":true}");using(var lease=new SystemDohRecoveryPreflight.MigrationFileLease(path,Work,64,false)){bool write=false,delete=false;try{await File.WriteAllTextAsync(path,"{}");}catch(IOException){write=true;}try{File.Delete(path);}catch(IOException){delete=true;}Require(write&&delete,"Held file mutable");lease.AssertOriginal();Require((await lease.ReadJsonAsync(default)).GetProperty("fixture").GetBoolean(),"State changed");}bool denied=false;try{using var lease=new SystemDohRecoveryPreflight.MigrationFileLease(path,Work,2,false);}catch(IOException){denied=true;}Require(denied,"Size bound absent");denied=false;try{using var lease=new SystemDohRecoveryPreflight.MigrationFileLease(path,Work,64);}catch(UnauthorizedAccessException){denied=true;}Require(denied,"User-owned private input admitted");}
 static void PrivateAclMigration(){
  var legacy=new FileSecurity();legacy.SetSecurityDescriptorSddlForm("O:BAG:BAD:AI(A;ID;0x1200a9;;;BU)(A;ID;FA;;;BA)(A;ID;FA;;;SY)");
  var rules=legacy.GetAccessRules(true,true,typeof(SecurityIdentifier)).Cast<FileSystemAccessRule>().ToArray();
  Require(!legacy.AreAccessRulesProtected&&rules.Length==3&&rules.Any(r=>r.IsInherited&&r.IdentityReference.Value=="S-1-5-32-545"&&(r.FileSystemRights&FileSystemRights.ReadData)!=0),"Fixture must reproduce genuine inherited legacy Users READ FileSecurity");
  void Denied(FileSecurity value,string reason){bool denied=false;try{SystemDohRecoveryPreflight.AssertPrivateAcl(value);}catch(UnauthorizedAccessException){denied=true;}Require(denied,reason);}
  Denied(legacy,"Native private guard admitted legacy exposed source");
  var admin=new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid,null);var users=new SecurityIdentifier(WellKnownSidType.BuiltinUsersSid,null);
  var canonical=ProtectedProductRoot.CreateFileAclForOwner(true,admin);SystemDohRecoveryPreflight.AssertPrivateAcl(canonical);
  Require(canonical.AreAccessRulesProtected&&canonical.GetAccessRules(true,true,typeof(SecurityIdentifier)).Count==2,"Canonical conversion must produce protected Admin/SYSTEM two-ACE contract");
  foreach(var access in new[]{FileSystemRights.ReadData,FileSystemRights.WriteData,FileSystemRights.AppendData,FileSystemRights.Delete,FileSystemRights.ChangePermissions,FileSystemRights.TakeOwnership}){var exposed=ProtectedProductRoot.CreateFileAclForOwner(true,admin);exposed.AddAccessRule(new FileSystemAccessRule(users,access,AccessControlType.Allow));Denied(exposed,"Canonical conversion admitted untrusted read/write/delete/permission mutation");}
  var wrongOwner=ProtectedProductRoot.CreateFileAclForOwner(true,admin);wrongOwner.SetOwner(users);Denied(wrongOwner,"Untrusted owner admitted after canonical conversion");
 }
 static int Port(){using var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();return((IPEndPoint)listener.LocalEndpoint).Port;}
 static async Task NativeFactsAsync(){using var child=new Process{StartInfo=new ProcessStartInfo(Xray){UseShellExecute=false,CreateNoWindow=true,RedirectStandardInput=true,RedirectStandardOutput=true,RedirectStandardError=true}};foreach(string arg in new[]{"run","-config","stdin:","-format","json"})child.StartInfo.ArgumentList.Add(arg);Require(child.Start(),"Fixture start failed");try{var identity=OwnedSystemDohProcess.ReadRuntimeIdentity(child.SafeHandle);var facts=SystemDohRecoveryPreflight.ReadMigrationProcessFacts(child,Xray,identity.Born,default);Require(facts.ParentPid==Environment.ProcessId&&facts.CommandLine.Contains("stdin:"),"Native facts wrong");bool denied=false;try{SystemDohRecoveryPreflight.ReadMigrationProcessFacts(child,Xray,identity.Born.AddTicks(1),default);}catch(InvalidDataException){denied=true;}Require(denied,"Reused birth admitted");Require(!SystemDohRecoveryPreflight.MigrationArgumentsSelect(facts.CommandLine,Xray,Path.Combine(Work,"expected.json"),true),"Foreign runtime config admitted");}finally{child.StandardInput.Close();if(!child.HasExited)child.Kill();await child.WaitForExitAsync().WaitAsync(TimeSpan.FromSeconds(1));}}
 static async Task CancellationAsync(){using var upstream=new UdpClient(new IPEndPoint(IPAddress.Loopback,0));using var cancel=new CancellationTokenSource(4500);int port=Port();var query=upstream.ReceiveAsync(cancel.Token);var probe=SystemDohRecoveryPreflight.ProbeContainedMigrationCandidateAsync(Xray,Candidate(port,((IPEndPoint)upstream.Client.LocalEndPoint!).Port),port,false,cancel.Token);await query.AsTask().WaitAsync(TimeSpan.FromSeconds(2));var clock=Stopwatch.StartNew();cancel.Cancel();bool cancelled=false;try{await probe;}catch(OperationCanceledException){cancelled=true;}Require(cancelled&&clock.Elapsed<TimeSpan.FromSeconds(1.5)&&SystemDohRecoveryPreflight.ReadRows(port,default).Length==0,"Cancellation retained child or exceeded cleanup bound");}
 static async Task ForcedOwnerExitAsync(){string id=Guid.NewGuid().ToString("N"),directory=Path.Combine(Work,"migration-owner-"+id);Directory.CreateDirectory(directory);string assembly=typeof(Program).Assembly.Location,source=Path.GetDirectoryName(assembly)!;foreach(string file in Directory.EnumerateFiles(source).Where(file=>Path.GetExtension(file) is ".dll" or ".json"))File.Copy(file,Path.Combine(directory,Path.GetFileName(file)));string host=Path.Combine(directory,"unique-migration-owner-"+id+".exe");File.Copy(Path.Combine(source,"CoreDnsMigrationPreflightRegression.exe"),host);using var upstream=new UdpClient(new IPEndPoint(IPAddress.Loopback,0));using var foreign=new UdpClient(new IPEndPoint(IPAddress.Loopback,0));int port=Port();using var owner=new Process{StartInfo=new ProcessStartInfo(host){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true}};owner.StartInfo.Environment["DOTNET_ROOT"]=Path.GetDirectoryName(Environment.ProcessPath)!;foreach(string arg in new[]{"--contained-owner-fixture",Work,Xray,port.ToString(),((IPEndPoint)upstream.Client.LocalEndPoint!).Port.ToString(),id})owner.StartInfo.ArgumentList.Add(arg);Require(owner.Start(),"Unique fixture owner failed");Process? child=null;DateTimeOffset birth=default;try{var ownerIdentity=OwnedSystemDohProcess.ReadRuntimeIdentity(owner.SafeHandle);var clock=Stopwatch.StartNew();while(true){var rows=SystemDohRecoveryPreflight.ReadRows(port,default);if(rows.Length>0&&rows.Select(row=>row.ProcessId).Distinct().Count()==1&&SystemDohRecoveryPreflight.OwnsEndpoints(rows,port,rows[0].ProcessId,false)){child=Process.GetProcessById(rows[0].ProcessId);var identity=OwnedSystemDohProcess.ReadRuntimeIdentity(child.SafeHandle);birth=identity.Born;Require(identity.Path.Equals(Xray,StringComparison.OrdinalIgnoreCase),"Foreign candidate fixture image");break;}Require(!owner.HasExited&&clock.Elapsed<TimeSpan.FromSeconds(2),"Owner did not bind isolated candidate: "+(owner.HasExited?await owner.StandardError.ReadToEndAsync():"timeout"));await Task.Delay(20);}OwnedSystemDohProcess.VerifyRuntimeIdentity(owner.SafeHandle,host,ownerIdentity.Born);owner.Kill();await owner.WaitForExitAsync().WaitAsync(TimeSpan.FromSeconds(1));bool exited=true;try{await child.WaitForExitAsync().WaitAsync(TimeSpan.FromSeconds(1));}catch(TimeoutException){exited=false;}Require(exited&&SystemDohRecoveryPreflight.ReadRows(port,default).Length==0,"Abrupt owner exit orphaned candidate/endpoints");int foreignPort=((IPEndPoint)foreign.Client.LocalEndPoint!).Port;Require(SystemDohRecoveryPreflight.ReadRows(foreignPort,default).Any(row=>row.ProcessId==Environment.ProcessId&&!row.Tcp),"Unrelated fixture listener was killed");}finally{if(!owner.HasExited){owner.Kill();await owner.WaitForExitAsync();}if(child!=null){if(!child.HasExited){OwnedSystemDohProcess.VerifyRuntimeIdentity(child.SafeHandle,Xray,birth);child.Kill();await child.WaitForExitAsync();}child.Dispose();}}}
 static string Candidate(int port,int upstream)=>JsonSerializer.Serialize(new{log=new{loglevel="none"},dns=new{tag="upstream",servers=new[]{new{address="127.0.0.1",port=upstream}},disableCache=true,queryStrategy="UseIPv4"},inbounds=new[]{new{tag="dns-in",listen="127.0.0.1",port,protocol="dokodemo-door",settings=new{address="1.1.1.1",port=53,network="tcp,udp"}}},outbounds=new[]{new{tag="dns-out",protocol="dns"},new{tag="direct",protocol="freedom"}},routing=new{rules=new[]{new{type="field",inboundTag=new[]{"upstream"},outboundTag="direct"},new{type="field",inboundTag=new[]{"dns-in"},outboundTag="dns-out"}}}});
 static async Task RealCandidateAsync(bool fail,bool changed){using var upstream=new UdpClient(new IPEndPoint(IPAddress.Loopback,0));using var stop=new CancellationTokenSource();int questions=0,assertions=0;var reader=Task.Run(async()=>{try{while(true){var question=await upstream.ReceiveAsync(stop.Token);questions++;if(!fail){var answer=question.Buffer.ToArray();answer[2]=0x81;answer[3]=0x83;Array.Clear(answer,6,6);await upstream.SendAsync(answer,question.RemoteEndPoint,stop.Token);}}}catch(OperationCanceledException){}});using var old=Process.GetCurrentProcess();var born=old.StartTime;int port=Port();using var deadline=new CancellationTokenSource(4500);bool ready=false;var clock=Stopwatch.StartNew();try{ready=await SystemDohRecoveryPreflight.ProbeMigrationCandidateAsync(Xray,Candidate(port,((IPEndPoint)upstream.Client.LocalEndPoint!).Port),port,false,token=>{token.ThrowIfCancellationRequested();Require(!old.HasExited&&old.StartTime==born,"Old fixture lost");assertions++;if(changed&&assertions==2)throw new IOException("Simulated production generation changed");return Task.CompletedTask;},deadline.Token);}catch(IOException)when(changed){}finally{stop.Cancel();await reader;}Require(ready==(!fail&&!changed)&&questions>0&&!old.HasExited&&old.StartTime==born,"Wrong readiness or old process damaged");Require(SystemDohRecoveryPreflight.ReadRows(port,default).Length==0&&Process.GetProcessesByName(Path.GetFileNameWithoutExtension(Xray)).Length==0,"Candidate process/endpoints retained");Require(clock.Elapsed<TimeSpan.FromSeconds(6),"Timeout cleanup bound exceeded");}
}
